refer to http://nbviewer.jupyter.org/github/danielfrg/word2vec/blob/master/examples/word2vec.ipynb

In [1]:
import word2vec

In [40]:
import os
import jieba

In [2]:
%load_ext autoreload
%autoreload 2

In [24]:
raw_data_path=r'C:\data\text.txt'
output_path=r'C:\data\output'
cut_data_path=os.path.join(output_path,'cut_text.txt')
phrases_data_path=os.path.join(output_path,'text_phrases')
model_path=os.path.join(output_path,'model.bin')

In [25]:
with open(raw_data_path,'rb') as fin,open(cut_data_path,'wb') as fout:
    lines_t=[]
    for line in fin:
        line=line.decode('utf-8').strip('\r\n ')
        line=' '.join(jieba.cut(line)).encode('utf-8')
        lines_t.append(line)
    fout.writelines(lines_t)

In [26]:
word2vec.word2phrase(cut_data_path,phrases_data_path,verbose=True)

Starting training using file C:\data\output\cut_text.txt

Vocab size (unigrams + bigrams): 4038
Words in train file: 8933


In [27]:
word2vec.word2vec(phrases_data_path, model_path, size=100, verbose=True)

Starting training using file C:\data\output\text_phrases
Vocab size: 320
Words in train file: 6546


In [28]:
model=word2vec.load(model_path)

In [31]:
model.vocab

array(['</s>', '的', '，', '、', '和', '党', '。', '委员会', '党员', '社会主义', '发展',
       '是', '在', '工作', '组织', '必须', '建设', '决定', '领导', '）', '坚持', '党组织',
       '人民', '有', '群众', '要', '由', '上级', '。（', '为', '；', '或', '中央委员会', '对',
       '纪律检查', '批准', '地方_各级', '。党', '可以', '中国共产党', '经济', '进行', '不', '中',
       '同级', '应当', '向', '代表', '选举', '了', '干部', '各级', '同', '讨论', '社会', '以',
       '加强', '代表大会', '中国', '文化', '问题', '国家', '地', '情况', '党的纪律', '现代化',
       '中国_特色', '思想', '机关', '中央', '新', '政治', '维护', '任何', '报告', '执行', '政策',
       '委员', '作出', '教育', '意见', '常务委员会', '下', '都', '要求', '。中国共产党', '产生',
       '原则', '方针', '制度', '人', '团结', '它', '监督', '正式', '保证', '并', '其他',
       '基层', '基本', '全体会议', '改革开放', '我国', '本', '按照', '事业', '实现', '民主',
       '书记', '全国代表大会', '又', '会议', '实行', '如果', '把', '一切', '利益', '候补委员',
       '反对', '自己', '毛泽东思想', '马克思列宁主义', '处分', '中央政治局', '马克思主义', '需要',
       '“_三个代表', '支部', '他们', '决议', '参加', '根据', '邓小平理论', '他', '基层组织', '道路',
       '下级组织', '重大_问题', '任务', '章程', '民族', '共产主义', '全面', '提出',

In [32]:
model.vectors.shape

(320, 100)

In [33]:
model['一个'][:10]

array([ 0.07728709,  0.07876651,  0.14674114,  0.11880864, -0.00691209,
       -0.07177114, -0.0776692 ,  0.13405345, -0.08056924,  0.0791682 ])

In [34]:
model.distance('增强','一个')

[('增强', '一个', 0.08977462387740573)]

In [35]:
# 未出现的词会抛出'KeyError'异常
indexes, metrics = model.similar("dog")

KeyError: 'dog'

In [38]:
indexes,metrics=model.similar('一个')
# 返回值是一个tuple，第一个元素是与“一个”相近词的ID，另一个是与相近词的cos距离
indexes,metrics

(array([229,  22,  54, 141,  76,  66, 274, 244,  28,  61], dtype=int64),
 array([0.25212186, 0.23254648, 0.22954168, 0.22903973, 0.19769931,
        0.19320882, 0.18705917, 0.17676441, 0.17396326, 0.16689   ]))

In [39]:
model.vocab[indexes]

array(['通过', '人民', '社会', '共产主义', '政策', '中国_特色', '四项', '听取', '。（', '国家'],
      dtype='<U78')

In [42]:
# tf.get_variable(intializer)
type(model.vectors)

numpy.ndarray

In [46]:
# get_text_idx(x_text,vocab)
type(model.vocab_hash)  # dict, word: id

dict

### gensim word2vec

In [1]:
chi_model=r'C:\data\sgns.financial.bigram-char'

In [2]:
from gensim.models.keyedvectors import KeyedVectors
w2v_model = KeyedVectors.load_word2vec_format(chi_model,binary=False,unicode_errors='ignore')

C:\Users\MengnanChen\Anaconda3\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [3]:
w2v_model.vocab

{'，': <gensim.models.keyedvectors.Vocab at 0x202406b3da0>,
 '的': <gensim.models.keyedvectors.Vocab at 0x202406b3cf8>,
 '。': <gensim.models.keyedvectors.Vocab at 0x202406b3e10>,
 '、': <gensim.models.keyedvectors.Vocab at 0x202406b3e48>,
 '2017': <gensim.models.keyedvectors.Vocab at 0x202406d1080>,
 '公司': <gensim.models.keyedvectors.Vocab at 0x202406d10b8>,
 '：': <gensim.models.keyedvectors.Vocab at 0x202406d10f0>,
 '和': <gensim.models.keyedvectors.Vocab at 0x20241fe1978>,
 '在': <gensim.models.keyedvectors.Vocab at 0x2024213d2e8>,
 '%': <gensim.models.keyedvectors.Vocab at 0x2024213d5f8>,
 '了': <gensim.models.keyedvectors.Vocab at 0x202421d8898>,
 '市场': <gensim.models.keyedvectors.Vocab at 0x202421ff438>,
 '“': <gensim.models.keyedvectors.Vocab at 0x202421ff470>,
 '”': <gensim.models.keyedvectors.Vocab at 0x202421ff4a8>,
 '是': <gensim.models.keyedvectors.Vocab at 0x202421ff4e0>,
 '）': <gensim.models.keyedvectors.Vocab at 0x202421ff518>,
 '亿元': <gensim.models.keyedvectors.Vocab at 0x20242

In [18]:
'是' in w2v_model.vocab

True

In [17]:
w2v_model.vocab[list(w2v_model.vocab.keys())[-1]].index

467161

In [4]:
w2v_model.vocab['，'].index

0

In [5]:
w2v_model.vocab['是'].index

14

In [6]:
word2index = {token: token_index for token_index, token in enumerate(w2v_model.index2word)} 
word2index['是']

14

In [57]:
w2v_model.wv

C:\Users\MengnanChen\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


In [59]:
# all word's array
# refer to: https://github.com/RaRe-Technologies/gensim/issues/1513
type(w2v_model.wv.syn0)

C:\Users\MengnanChen\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.
C:\Users\MengnanChen\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  """Entry point for launching an IPython kernel.


numpy.ndarray

In [19]:
import numpy as np

In [20]:
x=np.asarray([[1,2,3],[4,5,6]])

In [21]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
y=np.asarray([5,6,7])

In [29]:
y

array([5, 6, 7])

In [31]:
np.concatenate([x,[y]])

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [ ]:
def convert_data_to_index(string_data, wv):
    index_data = []
    for word in string_data:
        if word in wv:
            index_data.append(wv.vocab[word].index)
    return index_data

embedding_matrix = np.zeros((len(model.wv.vocab), vector_dim))
for i in range(len(model.wv.vocab)):
    embedding_vector = model.wv[model.wv.index2word[i]]
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector
        
# setup the embedding layer(Keras)
embeddings = Embedding(input_dim=embedding_matrix.shape[0], output_dim=embedding_matrix.shape[1],
                      weights=[embedding_matrix])

# embedding layer weights are frozen to avoid updating embeddings while training(TF)
saved_embeddings = tf.constant(embedding_matrix)
embedding = tf.Variable(initial_value=saved_embeddings, trainable=False)